SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `bugshot`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugshot`.`project` (
  `PPROJECT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DATE_CREATION` DATETIME NULL DEFAULT NULL,
  `DEPENDENCY_JAR` LONGBLOB NULL DEFAULT NULL,
  `DEPENDENCY_JAR_NAME` VARCHAR(255) NULL DEFAULT NULL,
  `DEPENDENCY_JAR_PATH` VARCHAR(255) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `JAR_NAME` VARCHAR(255) NULL DEFAULT NULL,
  `JAR_PATH` VARCHAR(255) NULL DEFAULT NULL,
  `PROJECT_NAME` VARCHAR(255) NOT NULL,
  `TEST_JAR` LONGBLOB NOT NULL,
  `DATE_MODIFICATION` DATETIME NULL DEFAULT NULL,
  `CLASS_COUUN` INT(11) NULL,
  `TEST_COUNT` INT(11) NULL,
  PRIMARY KEY (`PPROJECT_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugshot`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugshot`.`class` (
  `CLASS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` TEXT NULL DEFAULT NULL,
  `SUCCESS` TINYINT NOT NULL,
  `QUALIFIED_NAME` LONGTEXT NULL DEFAULT NULL,
  `PPROJECT_ID` BIGINT(20) NOT NULL,
  `EXCUTION_DATE` DATETIME NULL DEFAULT NULL,
  `NUMBER_TESTS` INT(11) NULL DEFAULT NULL,
  `RUN_TIME` BIGINT(20) NULL DEFAULT NULL,
  `NUMBER_FAILED_TESTS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CLASS_ID`),
  INDEX `FK_fl0bnbdq8cigssafami55wh1p` (`PPROJECT_ID` ASC),
  CONSTRAINT `FK_fl0bnbdq8cigssafami55wh1p`
    FOREIGN KEY (`PPROJECT_ID`)
    REFERENCES `bugshot`.`project` (`PPROJECT_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 767
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugshot`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugshot`.`test` (
  `TEST_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` TEXT NULL DEFAULT NULL,
  `CLASS_ID` INT(11) NOT NULL,
  `EXECUTION_DATE` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`TEST_ID`),
  INDEX `CLASSID_idx` (`CLASS_ID` ASC),
  CONSTRAINT `CLASSID`
    FOREIGN KEY (`CLASS_ID`)
    REFERENCES `bugshot`.`class` (`CLASS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1876
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugshot`.`execution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugshot`.`execution` (
  `EXECUTION_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` TEXT NULL,
  `PATH` TEXT NULL DEFAULT NULL,
  `EXECUTION_DATE` DATETIME NULL DEFAULT NULL,
  `TEST_ID` INT(11) NOT NULL,
  `FAILURE_REASON` LONGTEXT NULL DEFAULT NULL,
  `STATUS` TINYINT(1) NULL DEFAULT NULL,
  `RUN_TIME` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`EXECUTION_ID`),
  INDEX `TESTID_idx` (`TEST_ID` ASC),
  CONSTRAINT `TESTID`
    FOREIGN KEY (`TEST_ID`)
    REFERENCES `bugshot`.`test` (`TEST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 263
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugshot`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugshot`.`user` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NULL,
  `ROLE` VARCHAR(45) NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
